; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#include <idp.iss>

; sets a default value for AppVersion if this file is built from Inno Setup Compiler and not with GitHub Actions (see build-all-installers.yml and definition of MyAppVersion...)
; this default fallback value must ALWAYS, even when changed, be a name of some release tag on GitHub, e.g. "0.513" or otherwise local builds of this version specific installer will result in a 404 when trying to download from an invalid URL.
#ifndef AppVersion
  #define AppVersion "0.513"
#endif

#define MyAppName "Eugene font - SMuFL"
#define MyAppPublisher "Mikko Patama"
#define MyAppURL "https://github.com/mikkopatama/eugenefont"
; neat trick (that took way to long to come up with): AppVersion is automatically defined in build-all-installers.yml with 
; iscc /DAppVersion=${{ steps.get_tag.outputs.NEWEST_RELEASE_TAG_NAME }} which is directly fetched from the main git repo release tag names
; No manual changes to this file for version specific releases needed anymore.
#define MyAppVersion AppVersion

[Setup]
PrivilegesRequiredOverridesAllowed=dialog
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DC5F19DB-B324-43CE-B85C-1752AAAB8A57}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=Eugene-Win-{#MyAppVersion}
SolidCompression=yes
WizardStyle=classic dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

;fetch installable files from git via version specific release, make sure that all three files are under the release files

[Code]
procedure InitializeWizard();
var gitURL:string;
begin
  gitURL := 'https://github.com/mikkopatama/eugenefont/releases/download/' + ExpandConstant('{#MyAppVersion}') + '/';
  idpAddFile(gitURL + 'Eugene.json', ExpandConstant('{tmp}\Eugene.json'));
  idpAddFile(gitURL + 'EugeneText.otf', ExpandConstant('{tmp}\EugeneText.otf'));
  idpAddFile(gitURL + 'Eugene.otf', ExpandConstant('{tmp}\Eugene.otf'));
  idpDownloadAfter(wpReady);
end;

//get downloaded fonts from tmp

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    ForceDirectories(ExpandConstant('{localappdata}\Microsoft\Windows\Fonts'));
    ForceDirectories(ExpandConstant('{localappdata}\SMuFL\Fonts\Eugene'));
    FileCopy(ExpandConstant('{tmp}\EugeneText.otf'), ExpandConstant('{localappdata}\Microsoft\Windows\Fonts\EugeneText.otf'), False);
    FileCopy(ExpandConstant('{tmp}\Eugene.otf'), ExpandConstant('{localappdata}\Microsoft\Windows\Fonts\Eugene.otf'), False);
    FileCopy(ExpandConstant('{tmp}\Eugene.json'), ExpandConstant('{localappdata}\SMuFL\Fonts\Eugene\Eugene.json'), False);
  end;
end;

//register fonts as new keys to register

[Registry]
Root: HKCU; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"; \
    ValueType: string; \
    ValueName: "Eugene (OpenType)"; \
    ValueData: "{localappdata}\Microsoft\Windows\Fonts\Eugene.otf"

Root: HKCU; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"; \
    ValueType: string; \
    ValueName: "Eugene Text (OpenType)"; \
    ValueData: "{localappdata}\Microsoft\Windows\Fonts\EugeneText.otf"