; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#include <idp.iss>

#define MyAppName "Eugene font - SMuFL"
#define MyAppVersion "Eugene 0.513"
#define MyAppPublisher "Mikko Patama"
#define MyAppURL "https://github.com/mikkopatama/eugenefont"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DC5F19DB-B324-43CE-B85C-1752AAAB8A57}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputBaseFilename=Eugene Setup Wizard
SolidCompression=yes
WizardStyle=classic dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

;fetch installable files from git latest release

[Code]
procedure InitializeWizard();
begin
  idpAddFile('https://github.com/mikkopatama/eugenefont/releases/latest/download/Eugene.json', ExpandConstant('{tmp}\Eugene.json'));
  idpAddFile('https://github.com/mikkopatama/eugenefont/releases/latest/download/EugeneText.otf', ExpandConstant('{tmp}\EugeneText.otf'));
  idpAddFile('https://github.com/mikkopatama/eugenefont/releases/latest/download/Eugene.otf', ExpandConstant('{tmp}\Eugene.otf'));
  idpDownloadAfter(wpReady);
end;

//get downloaded fonts from tmp

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    FileCopy(ExpandConstant('{tmp}\EugeneText.otf'), ExpandConstant('{localappdata}\Microsoft\Windows\Fonts\EugeneText.otf'), False);
    FileCopy(ExpandConstant('{tmp}\Eugene.otf'), ExpandConstant('{localappdata}\Microsoft\Windows\Fonts\Eugene.otf'), False);
    FileCopy(ExpandConstant('{tmp}\Eugene.json'), ExpandConstant('{localappdata}\SMuFL\Fonts\Eugene\Eugene.json'), False);
  end;
end;

//register fonts as new keys to register

[Registry]
Root: HKCU; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"; \
    ValueType: string; \
    ValueName: "Eugene (OpenType)"; \
    ValueData: "{localappdata}\Microsoft\Windows\Fonts\Eugene.otf"

Root: HKCU; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"; \
    ValueType: string; \
    ValueName: "Eugene Text (OpenType)"; \
    ValueData: "{localappdata}\Microsoft\Windows\Fonts\EugeneText.otf"