name: Build Installer

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Install IDP plugin
        run: |
          $idpFetchAddress = "https://github.com/PeterDaveHello/inno-download-plugin/releases/download/v1.5.1/idpsetup-1.5.1.exe"
          Invoke-WebRequest -Uri $idpFetchAddress -OutFile "$env:TEMP\idpsetup-1.5.1.exe"
          Start-Process -FilePath "$env:TEMP\idpsetup-1.5.1.exe" -ArgumentList "/VERYSILENT /DIR=""C:\Program Files (x86)\Inno Setup 6""" -Wait
        shell: powershell

      - name: Compile installer
        run: iscc /DAppVersion=${{ github.ref_name }} Installers/Windows/Eugene-win-installscript.iss

      - name: Upload installer to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Installers/Windows/Output/Eugene-Win-install.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}